### ISSUE TITLE
Errors 😢

### ISSUE THREAD

**Issue by tobyweston** [gabro/scalaz2cats#12]
Running 

```sbt
sbt> scalafix github:gabro/scalaz2cats/Scalaz2cats_v1_0_0
```

I get

```scala
[error] (Compile / scalafix) scalafix.sbt.InvalidArgument: 23 errors
[error] [E0] /var/folders/wg/3nnv2yf90914pqpx69wmd9cc0000gn/T/scalafix1019091580112784306/Scalaz2cats_v1_0_0.scala9214355990756198611.scala:12:10 error: type mismatch;
[error]  found   : Symbol (in scala) 
[error]  required: Symbol (in scalafix.v0) 
[error]     Symbol("_root_.scalaz.`\\/`.")
[error]           ^
[error] 
```

Is that obvious to you what might be going on? I'm running SBT `1.2.7` and Scala `2.12.7`.

No worries, it was a long shot but thought I'd give running the scalafix it a try... 😄

**Comment by gabro** [comment]
Sorry, this would require an upgrade to the latest Scalafix API.

I suspect it's probably a small change and I would welcome a PR doing it, but I won't have time to work on in this in the near future.
